name: Generate Burndown Chart

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  burndown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate charts in Python container
        uses: docker://python:3.11-slim
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            bash -c "pip install matplotlib requests python-dateutil && python .github/scripts/burndown.py"

      - name: Commit burndown chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/*.png
          git commit -m "Update burndown charts [skip ci]" || echo "No changes to commit"
          git push 