name: Generate Burndown Chart

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  burndown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests python-dateutil

      - name: Generate burndown chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/burndown.py

      - name: Commit burndown chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/*.png
          git commit -m "Update burndown charts [skip ci]" || echo "No changes to commit"
          git push 